
export const CONFIG_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  REDIS_URL: 'REDIS_URL',
  RABBITMQ_URL: 'RABBITMQ_URL',
  OUTBOX_BATCH_SIZE: 'OUTBOX_BATCH_SIZE',
  OUTBOX_POLL_INTERVAL_MS: 'OUTBOX_POLL_INTERVAL_MS',
  JWT_SECRET: 'JWT_SECRET',
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  LOGIN_LOCK_THRESHOLD: 'LOGIN_LOCK_THRESHOLD',
  LOGIN_LOCK_DURATION_MINUTES: 'LOGIN_LOCK_DURATION_MINUTES',
  LOGIN_DELAY_CAP_SECONDS: 'LOGIN_DELAY_CAP_SECONDS',
  LOGIN_RATE_LIMIT_IP_PER_MINUTE: 'LOGIN_RATE_LIMIT_IP_PER_MINUTE',
  LOGIN_RATE_LIMIT_EMAIL_PER_MINUTE: 'LOGIN_RATE_LIMIT_EMAIL_PER_MINUTE',
  OUTBOX_MAX_RETRIES: 'OUTBOX_MAX_RETRIES',
  OUTBOX_RETRY_BASE_DELAY_MS: 'OUTBOX_RETRY_BASE_DELAY_MS',
  OUTBOX_CLAIM_TTL_MS: 'OUTBOX_CLAIM_TTL_MS',
  RABBITMQ_EVENTS_EXCHANGE: 'RABBITMQ_EVENTS_EXCHANGE',
  RABBITMQ_EVENTS_QUEUE: 'RABBITMQ_EVENTS_QUEUE',
  RABBITMQ_EVENTS_DLX: 'RABBITMQ_EVENTS_DLX',
  RABBITMQ_EVENTS_DLQ: 'RABBITMQ_EVENTS_DLQ',
  RABBITMQ_CONSUMER_CLAIM_TTL_MS: 'RABBITMQ_CONSUMER_CLAIM_TTL_MS',
  RABBITMQ_CONSUMER_PREFETCH: 'RABBITMQ_CONSUMER_PREFETCH',
  RABBITMQ_CONSUMER_MAX_RETRIES: 'RABBITMQ_CONSUMER_MAX_RETRIES',
  ALERT_OUTBOX_PENDING_THRESHOLD: 'ALERT_OUTBOX_PENDING_THRESHOLD',
  ALERT_OUTBOX_FAILED_THRESHOLD: 'ALERT_OUTBOX_FAILED_THRESHOLD',
  ALERT_CONSUMER_NACK_THRESHOLD: 'ALERT_CONSUMER_NACK_THRESHOLD',
  FRAUD_TRANSFER_MAX_AMOUNT: 'FRAUD_TRANSFER_MAX_AMOUNT',
  FRAUD_WITHDRAW_MAX_AMOUNT: 'FRAUD_WITHDRAW_MAX_AMOUNT',
  FRAUD_DAILY_TRANSFER_LIMIT: 'FRAUD_DAILY_TRANSFER_LIMIT',
  FRAUD_DAILY_WITHDRAW_LIMIT: 'FRAUD_DAILY_WITHDRAW_LIMIT',
  FRAUD_TRANSFERS_PER_MINUTE_LIMIT: 'FRAUD_TRANSFERS_PER_MINUTE_LIMIT',
  TRANSACTIONS_TRANSFER_RATE_LIMIT_PER_MINUTE:
    'TRANSACTIONS_TRANSFER_RATE_LIMIT_PER_MINUTE',
  TRANSACTIONS_IDEMPOTENCY_IN_FLIGHT_TTL_SEC:
    'TRANSACTIONS_IDEMPOTENCY_IN_FLIGHT_TTL_SEC',
} as const;

export type ConfigKey = (typeof CONFIG_KEYS)[keyof typeof CONFIG_KEYS];

export const MESSAGING_EXCHANGES = {
  BANKING_EVENTS: 'banking.events',
} as const;
