
export const CONFIG_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  REDIS_URL: 'REDIS_URL',
  RABBITMQ_URL: 'RABBITMQ_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  LOGIN_LOCK_THRESHOLD: 'LOGIN_LOCK_THRESHOLD',
  LOGIN_LOCK_DURATION_MINUTES: 'LOGIN_LOCK_DURATION_MINUTES',
  LOGIN_DELAY_CAP_SECONDS: 'LOGIN_DELAY_CAP_SECONDS',
  LOGIN_RATE_LIMIT_IP_PER_MINUTE: 'LOGIN_RATE_LIMIT_IP_PER_MINUTE',
  LOGIN_RATE_LIMIT_EMAIL_PER_MINUTE: 'LOGIN_RATE_LIMIT_EMAIL_PER_MINUTE',
} as const;

export type ConfigKey = (typeof CONFIG_KEYS)[keyof typeof CONFIG_KEYS];
